### ISSUE TITLE
Feature request: Add last tag pattern from which GHA will collect changelog

### ISSUE THREAD

**Issue by fabasoad** [simbo/changes-since-last-release-action#2]
This GHA works great for the projects with a single release process, though it is impossible to use if there are multiple release processes are present.

### Problem

Imagine that we have project with multiple **Dockerfile**s and we have a separate release process for each. For example, when we push tag `java-v1.2.3` then we release Dockerfile.java with it's own release changelog and when we push tag `go-v1.2.3` then we release `Dockerfile.go` with it's own release changelog. From this example for Dockerfile.java we need to collect all the logs between `java-v1.2.3` and latest `java-v*.*.*` tag. Same for `go-v*.*.*`.

### Suggestion

To have an additional input argument:

```yaml
- uses: simbo/changes-since-last-release-action@v2
  with:
    last-tag-pattern: "java-v*.*.*"
```

In this case we can achieve what we need to solve the issue above. By default `last-tag-pattern` will be `*` so that we do not change default behavior and won't introduce backward incompatibility.

**Comment by simbo** [comment]
This action is deprecated.
Please take a look at https://github.com/simbo/changes-between-tags-action, it should fulfill your needs.

**Comment by fabasoad** [comment]
Got it! Thank you for the link.
